### ISSUE TITLE
Disenchanting via shift-right click

### ISSUE THREAD

**Issue by cherryblight** [AstralOrdana/Spelunkery#269]
Whenever I shift-right click on anything, it disenchants my tools. This affected my shield and netherite sword when I shift-right-clicked on calcite in my survival world; and I have replicated this bug in creative using various stones, oak wood, and even oak leaves. I assume this may be an issue with Spelunkery, as it's the most recent mod I've updated esp considering it's changed some grindstone features. but it absolutely could be another mod.

Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.11
Moonlight Lib version: 1.20-2.12.17
Forge version: 47.2.0

**Mods that may be factoring into this bug:**
Apotheosis, Maybe? I'm not sure of any of the other mods that might but. I can list all 70 mods I have installed on that pack, if you need.

No crashes, just inconvienced. Lil upset I'll have to regain the enchantments on my tools.

**To Reproduce:**
1. Enchant tool
2. Shift-right click on a block

**Expected behavior:**
Not disenchanting when shift right clicking on non grindstone blocks 😓

**Comment by cherryblight** [comment]
Update: Tested the bug again with just spelunkery and moonlight lib on the same versions as og post, and then tested it again after updating moonlight lib with the same results

**Comment by Quarkrus** [comment]
> Update: Tested the bug again with just spelunkery and moonlight lib on the same versions as og post, and then tested it again after updating moonlight lib with the same results

The same thing, enchantments from any item disappear and give experience (Grindstone works exactly the same way by the way) if you press shift+right click on the ENTITY or block
Yes, even if you click on the entity, this bug will work

The update log says that the new version of spelunkery added the ability to remove enchantments from items by pressing shift+right-click on a grindstone but it seems that this feature works not only for it...

**Comment by Quarkrus** [comment]
IMPORTANT: Grindstones now remove curse enchantments from items, both by clicking on the grindstone and in the GUI

**Comment by AstralOrdana** [comment]
thats a real shwoopsie moment from me 
![image](https://github.com/user-attachments/assets/aa9befae-86f4-4001-a52a-063464b3f1ca)

**Comment by AstralOrdana** [comment]
> IMPORTANT: Grindstones now remove curse enchantments from items, both by clicking on the grindstone and in the GUI

that one is intentional, non-depleted diamond grindstones can grind curses

**Comment by FoxyTails1987** [comment]
Very much still a problem as I just updated from 2 updates before the latest, and now i lost my 259 XP Enchanted Supercharged Emerald Pickaxe’s hard earned enchantments with just accidentally clicking my homes River Wood Floor😭 im unable to use my shield as the enchantments also click off in a poof of XP

**Comment by AstralOrdana** [comment]
0.3.12 is scheduled for later today, it will fix this, im sorry its caused so much trouble

**Comment by FoxyTails1987** [comment]
Well least it can’t zap off the stuff on my Ruinrock Armor i’ll be fine not going mining or such in hope to not get mawled by a 8lvl Buffed Mutant Zombie glad to know i can look forward to mining later

**Comment by AstralOrdana** [comment]
fixed in 0.3.12

**Comment by FoxyTails1987** [comment]
It still is alittle broken it fixed the big bad bug but you still accidentally Disenchant a shield by a grindstone aswell as it has disabled the use of Shift click to grind Raw ores on the grindstone

**Comment by AstralOrdana** [comment]
bulk grinding was intentionally removed, also if you shift + click while holding a shield in your off hand, theres not a ton i can do about that without introducing weird exceptions

**Comment by FoxyTails1987** [comment]
This Problem still exists i dropped minecraft out of annoyance for awhile in hopes the bugs of the mods where fixed but this still happens even when i updated it finally
